### ISSUE TITLE
NullPointerException when launching the program

### ISSUE THREAD

**Issue by LouisH-760** [LouisH-760/MusicPlayer#9]
When trying to launch a built jar since after the new shortcut merge.

Error:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
Caused by: java.lang.NullPointerException
	at com.musicplayer.keyboard.ShortcutBinding.isIn(ShortcutBinding.java:81)
	at com.musicplayer.keyboard.ShortcutBinding.addBind(ShortcutBinding.java:68)
	at com.musicplayer.gui.SwingGUI.setNextAction(SwingGUI.java:132)
	at com.musicplayer.logic.SingleAlbumLogic.<init>(SingleAlbumLogic.java:70)
	at com.musicplayer.Main.main(Main.java:16)
	... 5 more
```

**Comment by LouisH-760** [comment]
Fixed by latest commit.
